/*
Doslano Integration API

Testing LettersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package doslano

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/doslano-ru/doslano-go"
)

func Test_doslano_LettersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LettersAPIService CreateLetter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LettersAPI.CreateLetter(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LettersAPIService DownloadRecipientInventoryPdf", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var recipientId string

		resp, httpRes, err := apiClient.LettersAPI.DownloadRecipientInventoryPdf(context.Background(), id, recipientId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LettersAPIService DownloadRecipientReceiptPdf", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var recipientId string

		resp, httpRes, err := apiClient.LettersAPI.DownloadRecipientReceiptPdf(context.Background(), id, recipientId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LettersAPIService GetLetter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.LettersAPI.GetLetter(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LettersAPIService GetRecipientTracking", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var recipientId string

		resp, httpRes, err := apiClient.LettersAPI.GetRecipientTracking(context.Background(), id, recipientId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LettersAPIService ListLetters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LettersAPI.ListLetters(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
