/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// DefaultAPIService DefaultAPI service
type DefaultAPIService service

type ApiOnLetterStatusChangedRequest struct {
	ctx context.Context
	ApiService *DefaultAPIService
	webhookEvent *WebhookEvent
}

func (r ApiOnLetterStatusChangedRequest) WebhookEvent(webhookEvent WebhookEvent) ApiOnLetterStatusChangedRequest {
	r.webhookEvent = &webhookEvent
	return r
}

func (r ApiOnLetterStatusChangedRequest) Execute() (*http.Response, error) {
	return r.ApiService.OnLetterStatusChangedExecute(r)
}

/*
OnLetterStatusChanged Колбек на финальный статус

Если при отправке письма указан `callback_url`, мы шлём на него POST при
достижении финального статуса — по каждому получателю
(`recipient.sent` / `recipient.failed`) и агрегатно по письму
(`letter.sent` / `letter.partial_failure` / `letter.failed` / `letter.cancelled`).

**Подпись.** Заголовок `X-Doslano-Signature: t=<unix>,v1=<hex>` — где
`v1 = HMAC_SHA256(secret, "<t>." + raw_body)`, `secret` — секрет аккаунта
из ЛК (раздел «API»). Проверьте подпись и свежесть `t` (±5 мин).

**Доставка.** At-least-once: ждём ответ `2xx`; иначе ретраим по
нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем
как недоставленный (видно в ЛК, можно переотправить). Дедуп — по `id`
события. Порядок не гарантируется — сверяйтесь со `status` в теле.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiOnLetterStatusChangedRequest
*/
func (a *DefaultAPIService) OnLetterStatusChanged(ctx context.Context) ApiOnLetterStatusChangedRequest {
	return ApiOnLetterStatusChangedRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *DefaultAPIService) OnLetterStatusChangedExecute(r ApiOnLetterStatusChangedRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.OnLetterStatusChanged")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/letterStatusChanged"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.webhookEvent == nil {
		return nil, reportError("webhookEvent is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.webhookEvent
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
