/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Pricing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Pricing{}

// Pricing struct for Pricing
type Pricing struct {
	// Итоговая списанная сумма, в копейках.
	TotalMinor int64 `json:"total_minor"`
	Currency string `json:"currency"`
	Promo *PromoResult `json:"promo,omitempty"`
}

type _Pricing Pricing

// NewPricing instantiates a new Pricing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricing(totalMinor int64, currency string) *Pricing {
	this := Pricing{}
	this.TotalMinor = totalMinor
	this.Currency = currency
	return &this
}

// NewPricingWithDefaults instantiates a new Pricing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricingWithDefaults() *Pricing {
	this := Pricing{}
	return &this
}

// GetTotalMinor returns the TotalMinor field value
func (o *Pricing) GetTotalMinor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalMinor
}

// GetTotalMinorOk returns a tuple with the TotalMinor field value
// and a boolean to check if the value has been set.
func (o *Pricing) GetTotalMinorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalMinor, true
}

// SetTotalMinor sets field value
func (o *Pricing) SetTotalMinor(v int64) {
	o.TotalMinor = v
}

// GetCurrency returns the Currency field value
func (o *Pricing) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *Pricing) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *Pricing) SetCurrency(v string) {
	o.Currency = v
}

// GetPromo returns the Promo field value if set, zero value otherwise.
func (o *Pricing) GetPromo() PromoResult {
	if o == nil || IsNil(o.Promo) {
		var ret PromoResult
		return ret
	}
	return *o.Promo
}

// GetPromoOk returns a tuple with the Promo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Pricing) GetPromoOk() (*PromoResult, bool) {
	if o == nil || IsNil(o.Promo) {
		return nil, false
	}
	return o.Promo, true
}

// HasPromo returns a boolean if a field has been set.
func (o *Pricing) HasPromo() bool {
	if o != nil && !IsNil(o.Promo) {
		return true
	}

	return false
}

// SetPromo gets a reference to the given PromoResult and assigns it to the Promo field.
func (o *Pricing) SetPromo(v PromoResult) {
	o.Promo = &v
}

func (o Pricing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Pricing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_minor"] = o.TotalMinor
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Promo) {
		toSerialize["promo"] = o.Promo
	}
	return toSerialize, nil
}

func (o *Pricing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_minor",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPricing := _Pricing{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPricing)

	if err != nil {
		return err
	}

	*o = Pricing(varPricing)

	return err
}

type NullablePricing struct {
	value *Pricing
	isSet bool
}

func (v NullablePricing) Get() *Pricing {
	return v.value
}

func (v *NullablePricing) Set(val *Pricing) {
	v.value = val
	v.isSet = true
}

func (v NullablePricing) IsSet() bool {
	return v.isSet
}

func (v *NullablePricing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricing(val *Pricing) *NullablePricing {
	return &NullablePricing{value: val, isSet: true}
}

func (v NullablePricing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


