/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"fmt"
)

// LetterClass Тип отправления. Пока поддерживается только заказное (`registered`).
type LetterClass string

// List of LetterClass
const (
	REGISTERED LetterClass = "registered"
)

// All allowed values of LetterClass enum
var AllowedLetterClassEnumValues = []LetterClass{
	"registered",
}

func (v *LetterClass) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LetterClass(value)
	for _, existing := range AllowedLetterClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LetterClass", value)
}

// NewLetterClassFromValue returns a pointer to a valid LetterClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLetterClassFromValue(v string) (*LetterClass, error) {
	ev := LetterClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LetterClass: valid values are %v", v, AllowedLetterClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LetterClass) IsValid() bool {
	for _, existing := range AllowedLetterClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LetterClass value
func (v LetterClass) Ptr() *LetterClass {
	return &v
}

type NullableLetterClass struct {
	value *LetterClass
	isSet bool
}

func (v NullableLetterClass) Get() *LetterClass {
	return v.value
}

func (v *NullableLetterClass) Set(val *LetterClass) {
	v.value = val
	v.isSet = true
}

func (v NullableLetterClass) IsSet() bool {
	return v.isSet
}

func (v *NullableLetterClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLetterClass(val *LetterClass) *NullableLetterClass {
	return &NullableLetterClass{value: val, isSet: true}
}

func (v NullableLetterClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLetterClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

