/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SenderInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SenderInput{}

// SenderInput struct for SenderInput
type SenderInput struct {
	// ФИО или название отправителя.
	Name string `json:"name"`
	// Адрес отправителя (строкой; нормализуется на нашей стороне).
	Address string `json:"address"`
	Email *string `json:"email,omitempty"`
	PartyType *PartyType `json:"party_type,omitempty"`
	// ИНН (для юр. лиц/ИП).
	Inn *string `json:"inn,omitempty"`
}

type _SenderInput SenderInput

// NewSenderInput instantiates a new SenderInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderInput(name string, address string) *SenderInput {
	this := SenderInput{}
	this.Name = name
	this.Address = address
	return &this
}

// NewSenderInputWithDefaults instantiates a new SenderInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderInputWithDefaults() *SenderInput {
	this := SenderInput{}
	return &this
}

// GetName returns the Name field value
func (o *SenderInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SenderInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SenderInput) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *SenderInput) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *SenderInput) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *SenderInput) SetAddress(v string) {
	o.Address = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SenderInput) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SenderInput) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SenderInput) SetEmail(v string) {
	o.Email = &v
}

// GetPartyType returns the PartyType field value if set, zero value otherwise.
func (o *SenderInput) GetPartyType() PartyType {
	if o == nil || IsNil(o.PartyType) {
		var ret PartyType
		return ret
	}
	return *o.PartyType
}

// GetPartyTypeOk returns a tuple with the PartyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetPartyTypeOk() (*PartyType, bool) {
	if o == nil || IsNil(o.PartyType) {
		return nil, false
	}
	return o.PartyType, true
}

// HasPartyType returns a boolean if a field has been set.
func (o *SenderInput) HasPartyType() bool {
	if o != nil && !IsNil(o.PartyType) {
		return true
	}

	return false
}

// SetPartyType gets a reference to the given PartyType and assigns it to the PartyType field.
func (o *SenderInput) SetPartyType(v PartyType) {
	o.PartyType = &v
}

// GetInn returns the Inn field value if set, zero value otherwise.
func (o *SenderInput) GetInn() string {
	if o == nil || IsNil(o.Inn) {
		var ret string
		return ret
	}
	return *o.Inn
}

// GetInnOk returns a tuple with the Inn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetInnOk() (*string, bool) {
	if o == nil || IsNil(o.Inn) {
		return nil, false
	}
	return o.Inn, true
}

// HasInn returns a boolean if a field has been set.
func (o *SenderInput) HasInn() bool {
	if o != nil && !IsNil(o.Inn) {
		return true
	}

	return false
}

// SetInn gets a reference to the given string and assigns it to the Inn field.
func (o *SenderInput) SetInn(v string) {
	o.Inn = &v
}

func (o SenderInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SenderInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.PartyType) {
		toSerialize["party_type"] = o.PartyType
	}
	if !IsNil(o.Inn) {
		toSerialize["inn"] = o.Inn
	}
	return toSerialize, nil
}

func (o *SenderInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSenderInput := _SenderInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSenderInput)

	if err != nil {
		return err
	}

	*o = SenderInput(varSenderInput)

	return err
}

type NullableSenderInput struct {
	value *SenderInput
	isSet bool
}

func (v NullableSenderInput) Get() *SenderInput {
	return v.value
}

func (v *NullableSenderInput) Set(val *SenderInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderInput(val *SenderInput) *NullableSenderInput {
	return &NullableSenderInput{value: val, isSet: true}
}

func (v NullableSenderInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


