/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateLetterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLetterRequest{}

// CreateLetterRequest struct for CreateLetterRequest
type CreateLetterRequest struct {
	// Отправитель. Если не указан — берётся отправитель по умолчанию из профиля аккаунта.
	Sender *SenderInput `json:"sender,omitempty"`
	Recipients []RecipientInput `json:"recipients"`
	Content LetterContent `json:"content"`
	LetterClass *LetterClass `json:"letter_class,omitempty"`
	// Промокод (опционально).
	PromoCode *string `json:"promo_code,omitempty"`
	// Что делать, если промокод не применился: `ignore` — отправить без скидки и вернуть пометку в `pricing.promo`; `reject` — отклонить (422). 
	OnPromoInvalid *string `json:"on_promo_invalid,omitempty"`
	// Что делать при нехватке средств: `reject` — отклонить (402), письмо не создаётся; `hold` — создать письмо в статусе `awaiting_payment`, оно оплатится автоматически при пополнении баланса. 
	OnInsufficientFunds *string `json:"on_insufficient_funds,omitempty"`
	// Пробный прогон: запрос проходит ПОЛНУЮ реальную валидацию (ключ, scope, IP, файлы, адреса получателей, промокод) и возвращает расчёт цены — но письмо в итоге не создаётся и средства не списываются. Ответ — `200` со схемой `DryRunResult` (вместо `201`/`Letter`). Ошибки валидации возвращаются теми же кодами, что и при реальной отправке (400/422) — это честный тест интеграции. `Idempotency-Key` при `dry_run` игнорируется; `callback_url` не регистрируется; баланс НЕ проверяется (тестируйте хоть с нулевым балансом — сумма к списанию будет в `pricing.total_minor`). 
	DryRun *bool `json:"dry_run,omitempty"`
	// HTTPS-URL для колбеков по этому письму. Если не указан — используйте поллинг.
	CallbackUrl *string `json:"callback_url,omitempty"`
}

type _CreateLetterRequest CreateLetterRequest

// NewCreateLetterRequest instantiates a new CreateLetterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLetterRequest(recipients []RecipientInput, content LetterContent) *CreateLetterRequest {
	this := CreateLetterRequest{}
	this.Recipients = recipients
	this.Content = content
	var letterClass LetterClass = LETTERCLASS_REGISTERED
	this.LetterClass = &letterClass
	var onPromoInvalid string = "ignore"
	this.OnPromoInvalid = &onPromoInvalid
	var onInsufficientFunds string = "reject"
	this.OnInsufficientFunds = &onInsufficientFunds
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// NewCreateLetterRequestWithDefaults instantiates a new CreateLetterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLetterRequestWithDefaults() *CreateLetterRequest {
	this := CreateLetterRequest{}
	var letterClass LetterClass = LETTERCLASS_REGISTERED
	this.LetterClass = &letterClass
	var onPromoInvalid string = "ignore"
	this.OnPromoInvalid = &onPromoInvalid
	var onInsufficientFunds string = "reject"
	this.OnInsufficientFunds = &onInsufficientFunds
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *CreateLetterRequest) GetSender() SenderInput {
	if o == nil || IsNil(o.Sender) {
		var ret SenderInput
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetSenderOk() (*SenderInput, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *CreateLetterRequest) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given SenderInput and assigns it to the Sender field.
func (o *CreateLetterRequest) SetSender(v SenderInput) {
	o.Sender = &v
}

// GetRecipients returns the Recipients field value
func (o *CreateLetterRequest) GetRecipients() []RecipientInput {
	if o == nil {
		var ret []RecipientInput
		return ret
	}

	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetRecipientsOk() ([]RecipientInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recipients, true
}

// SetRecipients sets field value
func (o *CreateLetterRequest) SetRecipients(v []RecipientInput) {
	o.Recipients = v
}

// GetContent returns the Content field value
func (o *CreateLetterRequest) GetContent() LetterContent {
	if o == nil {
		var ret LetterContent
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetContentOk() (*LetterContent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CreateLetterRequest) SetContent(v LetterContent) {
	o.Content = v
}

// GetLetterClass returns the LetterClass field value if set, zero value otherwise.
func (o *CreateLetterRequest) GetLetterClass() LetterClass {
	if o == nil || IsNil(o.LetterClass) {
		var ret LetterClass
		return ret
	}
	return *o.LetterClass
}

// GetLetterClassOk returns a tuple with the LetterClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetLetterClassOk() (*LetterClass, bool) {
	if o == nil || IsNil(o.LetterClass) {
		return nil, false
	}
	return o.LetterClass, true
}

// HasLetterClass returns a boolean if a field has been set.
func (o *CreateLetterRequest) HasLetterClass() bool {
	if o != nil && !IsNil(o.LetterClass) {
		return true
	}

	return false
}

// SetLetterClass gets a reference to the given LetterClass and assigns it to the LetterClass field.
func (o *CreateLetterRequest) SetLetterClass(v LetterClass) {
	o.LetterClass = &v
}

// GetPromoCode returns the PromoCode field value if set, zero value otherwise.
func (o *CreateLetterRequest) GetPromoCode() string {
	if o == nil || IsNil(o.PromoCode) {
		var ret string
		return ret
	}
	return *o.PromoCode
}

// GetPromoCodeOk returns a tuple with the PromoCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetPromoCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PromoCode) {
		return nil, false
	}
	return o.PromoCode, true
}

// HasPromoCode returns a boolean if a field has been set.
func (o *CreateLetterRequest) HasPromoCode() bool {
	if o != nil && !IsNil(o.PromoCode) {
		return true
	}

	return false
}

// SetPromoCode gets a reference to the given string and assigns it to the PromoCode field.
func (o *CreateLetterRequest) SetPromoCode(v string) {
	o.PromoCode = &v
}

// GetOnPromoInvalid returns the OnPromoInvalid field value if set, zero value otherwise.
func (o *CreateLetterRequest) GetOnPromoInvalid() string {
	if o == nil || IsNil(o.OnPromoInvalid) {
		var ret string
		return ret
	}
	return *o.OnPromoInvalid
}

// GetOnPromoInvalidOk returns a tuple with the OnPromoInvalid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetOnPromoInvalidOk() (*string, bool) {
	if o == nil || IsNil(o.OnPromoInvalid) {
		return nil, false
	}
	return o.OnPromoInvalid, true
}

// HasOnPromoInvalid returns a boolean if a field has been set.
func (o *CreateLetterRequest) HasOnPromoInvalid() bool {
	if o != nil && !IsNil(o.OnPromoInvalid) {
		return true
	}

	return false
}

// SetOnPromoInvalid gets a reference to the given string and assigns it to the OnPromoInvalid field.
func (o *CreateLetterRequest) SetOnPromoInvalid(v string) {
	o.OnPromoInvalid = &v
}

// GetOnInsufficientFunds returns the OnInsufficientFunds field value if set, zero value otherwise.
func (o *CreateLetterRequest) GetOnInsufficientFunds() string {
	if o == nil || IsNil(o.OnInsufficientFunds) {
		var ret string
		return ret
	}
	return *o.OnInsufficientFunds
}

// GetOnInsufficientFundsOk returns a tuple with the OnInsufficientFunds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetOnInsufficientFundsOk() (*string, bool) {
	if o == nil || IsNil(o.OnInsufficientFunds) {
		return nil, false
	}
	return o.OnInsufficientFunds, true
}

// HasOnInsufficientFunds returns a boolean if a field has been set.
func (o *CreateLetterRequest) HasOnInsufficientFunds() bool {
	if o != nil && !IsNil(o.OnInsufficientFunds) {
		return true
	}

	return false
}

// SetOnInsufficientFunds gets a reference to the given string and assigns it to the OnInsufficientFunds field.
func (o *CreateLetterRequest) SetOnInsufficientFunds(v string) {
	o.OnInsufficientFunds = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *CreateLetterRequest) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *CreateLetterRequest) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *CreateLetterRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *CreateLetterRequest) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLetterRequest) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *CreateLetterRequest) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *CreateLetterRequest) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

func (o CreateLetterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLetterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	toSerialize["recipients"] = o.Recipients
	toSerialize["content"] = o.Content
	if !IsNil(o.LetterClass) {
		toSerialize["letter_class"] = o.LetterClass
	}
	if !IsNil(o.PromoCode) {
		toSerialize["promo_code"] = o.PromoCode
	}
	if !IsNil(o.OnPromoInvalid) {
		toSerialize["on_promo_invalid"] = o.OnPromoInvalid
	}
	if !IsNil(o.OnInsufficientFunds) {
		toSerialize["on_insufficient_funds"] = o.OnInsufficientFunds
	}
	if !IsNil(o.DryRun) {
		toSerialize["dry_run"] = o.DryRun
	}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callback_url"] = o.CallbackUrl
	}
	return toSerialize, nil
}

func (o *CreateLetterRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipients",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLetterRequest := _CreateLetterRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateLetterRequest)

	if err != nil {
		return err
	}

	*o = CreateLetterRequest(varCreateLetterRequest)

	return err
}

type NullableCreateLetterRequest struct {
	value *CreateLetterRequest
	isSet bool
}

func (v NullableCreateLetterRequest) Get() *CreateLetterRequest {
	return v.value
}

func (v *NullableCreateLetterRequest) Set(val *CreateLetterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLetterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLetterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLetterRequest(val *CreateLetterRequest) *NullableCreateLetterRequest {
	return &NullableCreateLetterRequest{value: val, isSet: true}
}

func (v NullableCreateLetterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLetterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


