/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Letter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Letter{}

// Letter struct for Letter
type Letter struct {
	Id string `json:"id"`
	// Канал создания письма — `api` (этот API) или `web` (личный кабинет).
	Channel string `json:"channel"`
	Status LetterStatus `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	Sender *Party `json:"sender,omitempty"`
	Recipients []Recipient `json:"recipients"`
	Pricing Pricing `json:"pricing"`
	Payment *PaymentResult `json:"payment,omitempty"`
	CallbackUrl *string `json:"callback_url,omitempty"`
}

type _Letter Letter

// NewLetter instantiates a new Letter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLetter(id string, channel string, status LetterStatus, createdAt time.Time, recipients []Recipient, pricing Pricing) *Letter {
	this := Letter{}
	this.Id = id
	this.Channel = channel
	this.Status = status
	this.CreatedAt = createdAt
	this.Recipients = recipients
	this.Pricing = pricing
	return &this
}

// NewLetterWithDefaults instantiates a new Letter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLetterWithDefaults() *Letter {
	this := Letter{}
	return &this
}

// GetId returns the Id field value
func (o *Letter) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Letter) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Letter) SetId(v string) {
	o.Id = v
}

// GetChannel returns the Channel field value
func (o *Letter) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *Letter) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *Letter) SetChannel(v string) {
	o.Channel = v
}

// GetStatus returns the Status field value
func (o *Letter) GetStatus() LetterStatus {
	if o == nil {
		var ret LetterStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Letter) GetStatusOk() (*LetterStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Letter) SetStatus(v LetterStatus) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Letter) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Letter) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Letter) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *Letter) GetSender() Party {
	if o == nil || IsNil(o.Sender) {
		var ret Party
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Letter) GetSenderOk() (*Party, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *Letter) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given Party and assigns it to the Sender field.
func (o *Letter) SetSender(v Party) {
	o.Sender = &v
}

// GetRecipients returns the Recipients field value
func (o *Letter) GetRecipients() []Recipient {
	if o == nil {
		var ret []Recipient
		return ret
	}

	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value
// and a boolean to check if the value has been set.
func (o *Letter) GetRecipientsOk() ([]Recipient, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recipients, true
}

// SetRecipients sets field value
func (o *Letter) SetRecipients(v []Recipient) {
	o.Recipients = v
}

// GetPricing returns the Pricing field value
func (o *Letter) GetPricing() Pricing {
	if o == nil {
		var ret Pricing
		return ret
	}

	return o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value
// and a boolean to check if the value has been set.
func (o *Letter) GetPricingOk() (*Pricing, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pricing, true
}

// SetPricing sets field value
func (o *Letter) SetPricing(v Pricing) {
	o.Pricing = v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *Letter) GetPayment() PaymentResult {
	if o == nil || IsNil(o.Payment) {
		var ret PaymentResult
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Letter) GetPaymentOk() (*PaymentResult, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *Letter) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given PaymentResult and assigns it to the Payment field.
func (o *Letter) SetPayment(v PaymentResult) {
	o.Payment = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *Letter) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Letter) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *Letter) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *Letter) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

func (o Letter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Letter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["channel"] = o.Channel
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	toSerialize["recipients"] = o.Recipients
	toSerialize["pricing"] = o.Pricing
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callback_url"] = o.CallbackUrl
	}
	return toSerialize, nil
}

func (o *Letter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"channel",
		"status",
		"created_at",
		"recipients",
		"pricing",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLetter := _Letter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLetter)

	if err != nil {
		return err
	}

	*o = Letter(varLetter)

	return err
}

type NullableLetter struct {
	value *Letter
	isSet bool
}

func (v NullableLetter) Get() *Letter {
	return v.value
}

func (v *NullableLetter) Set(val *Letter) {
	v.value = val
	v.isSet = true
}

func (v NullableLetter) IsSet() bool {
	return v.isSet
}

func (v *NullableLetter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLetter(val *Letter) *NullableLetter {
	return &NullableLetter{value: val, isSet: true}
}

func (v NullableLetter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLetter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


