/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"time"
)

// checks if the TrackingInfoEventsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackingInfoEventsInner{}

// TrackingInfoEventsInner struct for TrackingInfoEventsInner
type TrackingInfoEventsInner struct {
	Code *string `json:"code,omitempty"`
	Name *string `json:"name,omitempty"`
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
	Location *string `json:"location,omitempty"`
}

// NewTrackingInfoEventsInner instantiates a new TrackingInfoEventsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackingInfoEventsInner() *TrackingInfoEventsInner {
	this := TrackingInfoEventsInner{}
	return &this
}

// NewTrackingInfoEventsInnerWithDefaults instantiates a new TrackingInfoEventsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackingInfoEventsInnerWithDefaults() *TrackingInfoEventsInner {
	this := TrackingInfoEventsInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *TrackingInfoEventsInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingInfoEventsInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *TrackingInfoEventsInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *TrackingInfoEventsInner) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TrackingInfoEventsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingInfoEventsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TrackingInfoEventsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TrackingInfoEventsInner) SetName(v string) {
	o.Name = &v
}

// GetOccurredAt returns the OccurredAt field value if set, zero value otherwise.
func (o *TrackingInfoEventsInner) GetOccurredAt() time.Time {
	if o == nil || IsNil(o.OccurredAt) {
		var ret time.Time
		return ret
	}
	return *o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingInfoEventsInner) GetOccurredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OccurredAt) {
		return nil, false
	}
	return o.OccurredAt, true
}

// HasOccurredAt returns a boolean if a field has been set.
func (o *TrackingInfoEventsInner) HasOccurredAt() bool {
	if o != nil && !IsNil(o.OccurredAt) {
		return true
	}

	return false
}

// SetOccurredAt gets a reference to the given time.Time and assigns it to the OccurredAt field.
func (o *TrackingInfoEventsInner) SetOccurredAt(v time.Time) {
	o.OccurredAt = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *TrackingInfoEventsInner) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingInfoEventsInner) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *TrackingInfoEventsInner) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *TrackingInfoEventsInner) SetLocation(v string) {
	o.Location = &v
}

func (o TrackingInfoEventsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackingInfoEventsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OccurredAt) {
		toSerialize["occurred_at"] = o.OccurredAt
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	return toSerialize, nil
}

type NullableTrackingInfoEventsInner struct {
	value *TrackingInfoEventsInner
	isSet bool
}

func (v NullableTrackingInfoEventsInner) Get() *TrackingInfoEventsInner {
	return v.value
}

func (v *NullableTrackingInfoEventsInner) Set(val *TrackingInfoEventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackingInfoEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackingInfoEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackingInfoEventsInner(val *TrackingInfoEventsInner) *NullableTrackingInfoEventsInner {
	return &NullableTrackingInfoEventsInner{value: val, isSet: true}
}

func (v NullableTrackingInfoEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackingInfoEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


