/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListLetters200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLetters200Response{}

// ListLetters200Response struct for ListLetters200Response
type ListLetters200Response struct {
	Data []Letter `json:"data"`
	HasMore bool `json:"has_more"`
}

type _ListLetters200Response ListLetters200Response

// NewListLetters200Response instantiates a new ListLetters200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLetters200Response(data []Letter, hasMore bool) *ListLetters200Response {
	this := ListLetters200Response{}
	this.Data = data
	this.HasMore = hasMore
	return &this
}

// NewListLetters200ResponseWithDefaults instantiates a new ListLetters200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLetters200ResponseWithDefaults() *ListLetters200Response {
	this := ListLetters200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListLetters200Response) GetData() []Letter {
	if o == nil {
		var ret []Letter
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListLetters200Response) GetDataOk() ([]Letter, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListLetters200Response) SetData(v []Letter) {
	o.Data = v
}

// GetHasMore returns the HasMore field value
func (o *ListLetters200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListLetters200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListLetters200Response) SetHasMore(v bool) {
	o.HasMore = v
}

func (o ListLetters200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLetters200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["has_more"] = o.HasMore
	return toSerialize, nil
}

func (o *ListLetters200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"has_more",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListLetters200Response := _ListLetters200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListLetters200Response)

	if err != nil {
		return err
	}

	*o = ListLetters200Response(varListLetters200Response)

	return err
}

type NullableListLetters200Response struct {
	value *ListLetters200Response
	isSet bool
}

func (v NullableListLetters200Response) Get() *ListLetters200Response {
	return v.value
}

func (v *NullableListLetters200Response) Set(val *ListLetters200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLetters200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLetters200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLetters200Response(val *ListLetters200Response) *NullableListLetters200Response {
	return &NullableListLetters200Response{value: val, isSet: true}
}

func (v NullableListLetters200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLetters200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


