/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"fmt"
)

// RecipientStatus Статус отправления получателю. `sent` — присвоен трек-номер Почты; финальные: `delivered`, `failed`. 
type RecipientStatus string

// List of RecipientStatus
const (
	RECIPIENTSTATUS_PENDING RecipientStatus = "pending"
	RECIPIENTSTATUS_QUEUED RecipientStatus = "queued"
	RECIPIENTSTATUS_SENDING RecipientStatus = "sending"
	RECIPIENTSTATUS_SENT RecipientStatus = "sent"
	RECIPIENTSTATUS_DELIVERED RecipientStatus = "delivered"
	RECIPIENTSTATUS_FAILED RecipientStatus = "failed"
)

// All allowed values of RecipientStatus enum
var AllowedRecipientStatusEnumValues = []RecipientStatus{
	"pending",
	"queued",
	"sending",
	"sent",
	"delivered",
	"failed",
}

func (v *RecipientStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RecipientStatus(value)
	for _, existing := range AllowedRecipientStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RecipientStatus", value)
}

// NewRecipientStatusFromValue returns a pointer to a valid RecipientStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRecipientStatusFromValue(v string) (*RecipientStatus, error) {
	ev := RecipientStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RecipientStatus: valid values are %v", v, AllowedRecipientStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RecipientStatus) IsValid() bool {
	for _, existing := range AllowedRecipientStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RecipientStatus value
func (v RecipientStatus) Ptr() *RecipientStatus {
	return &v
}

type NullableRecipientStatus struct {
	value *RecipientStatus
	isSet bool
}

func (v NullableRecipientStatus) Get() *RecipientStatus {
	return v.value
}

func (v *NullableRecipientStatus) Set(val *RecipientStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRecipientStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRecipientStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecipientStatus(val *RecipientStatus) *NullableRecipientStatus {
	return &NullableRecipientStatus{value: val, isSet: true}
}

func (v NullableRecipientStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecipientStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

