/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEventData{}

// WebhookEventData struct for WebhookEventData
type WebhookEventData struct {
	LetterId string `json:"letter_id"`
	RecipientId *string `json:"recipient_id,omitempty"`
	Status string `json:"status"`
	ShipmentNumber *string `json:"shipment_number,omitempty"`
	TrackingNumber *string `json:"tracking_number,omitempty"`
	Error *string `json:"error,omitempty"`
	// Фактически списанная стоимость отправления ЭТОМУ получателю, в копейках (доля дисконтированного тотала письма с учётом промокода). Присутствует только в `recipient.sent` — отправление реально ушло и оплачено. В `recipient.failed` отсутствует: при провале сумма возвращается на баланс.
	AmountMinor *int32 `json:"amount_minor,omitempty"`
}

type _WebhookEventData WebhookEventData

// NewWebhookEventData instantiates a new WebhookEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEventData(letterId string, status string) *WebhookEventData {
	this := WebhookEventData{}
	this.LetterId = letterId
	this.Status = status
	return &this
}

// NewWebhookEventDataWithDefaults instantiates a new WebhookEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEventDataWithDefaults() *WebhookEventData {
	this := WebhookEventData{}
	return &this
}

// GetLetterId returns the LetterId field value
func (o *WebhookEventData) GetLetterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LetterId
}

// GetLetterIdOk returns a tuple with the LetterId field value
// and a boolean to check if the value has been set.
func (o *WebhookEventData) GetLetterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LetterId, true
}

// SetLetterId sets field value
func (o *WebhookEventData) SetLetterId(v string) {
	o.LetterId = v
}

// GetRecipientId returns the RecipientId field value if set, zero value otherwise.
func (o *WebhookEventData) GetRecipientId() string {
	if o == nil || IsNil(o.RecipientId) {
		var ret string
		return ret
	}
	return *o.RecipientId
}

// GetRecipientIdOk returns a tuple with the RecipientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEventData) GetRecipientIdOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientId) {
		return nil, false
	}
	return o.RecipientId, true
}

// HasRecipientId returns a boolean if a field has been set.
func (o *WebhookEventData) HasRecipientId() bool {
	if o != nil && !IsNil(o.RecipientId) {
		return true
	}

	return false
}

// SetRecipientId gets a reference to the given string and assigns it to the RecipientId field.
func (o *WebhookEventData) SetRecipientId(v string) {
	o.RecipientId = &v
}

// GetStatus returns the Status field value
func (o *WebhookEventData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookEventData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookEventData) SetStatus(v string) {
	o.Status = v
}

// GetShipmentNumber returns the ShipmentNumber field value if set, zero value otherwise.
func (o *WebhookEventData) GetShipmentNumber() string {
	if o == nil || IsNil(o.ShipmentNumber) {
		var ret string
		return ret
	}
	return *o.ShipmentNumber
}

// GetShipmentNumberOk returns a tuple with the ShipmentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEventData) GetShipmentNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ShipmentNumber) {
		return nil, false
	}
	return o.ShipmentNumber, true
}

// HasShipmentNumber returns a boolean if a field has been set.
func (o *WebhookEventData) HasShipmentNumber() bool {
	if o != nil && !IsNil(o.ShipmentNumber) {
		return true
	}

	return false
}

// SetShipmentNumber gets a reference to the given string and assigns it to the ShipmentNumber field.
func (o *WebhookEventData) SetShipmentNumber(v string) {
	o.ShipmentNumber = &v
}

// GetTrackingNumber returns the TrackingNumber field value if set, zero value otherwise.
func (o *WebhookEventData) GetTrackingNumber() string {
	if o == nil || IsNil(o.TrackingNumber) {
		var ret string
		return ret
	}
	return *o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEventData) GetTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingNumber) {
		return nil, false
	}
	return o.TrackingNumber, true
}

// HasTrackingNumber returns a boolean if a field has been set.
func (o *WebhookEventData) HasTrackingNumber() bool {
	if o != nil && !IsNil(o.TrackingNumber) {
		return true
	}

	return false
}

// SetTrackingNumber gets a reference to the given string and assigns it to the TrackingNumber field.
func (o *WebhookEventData) SetTrackingNumber(v string) {
	o.TrackingNumber = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *WebhookEventData) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEventData) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *WebhookEventData) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *WebhookEventData) SetError(v string) {
	o.Error = &v
}

// GetAmountMinor returns the AmountMinor field value if set, zero value otherwise.
func (o *WebhookEventData) GetAmountMinor() int32 {
	if o == nil || IsNil(o.AmountMinor) {
		var ret int32
		return ret
	}
	return *o.AmountMinor
}

// GetAmountMinorOk returns a tuple with the AmountMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEventData) GetAmountMinorOk() (*int32, bool) {
	if o == nil || IsNil(o.AmountMinor) {
		return nil, false
	}
	return o.AmountMinor, true
}

// HasAmountMinor returns a boolean if a field has been set.
func (o *WebhookEventData) HasAmountMinor() bool {
	if o != nil && !IsNil(o.AmountMinor) {
		return true
	}

	return false
}

// SetAmountMinor gets a reference to the given int32 and assigns it to the AmountMinor field.
func (o *WebhookEventData) SetAmountMinor(v int32) {
	o.AmountMinor = &v
}

func (o WebhookEventData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["letter_id"] = o.LetterId
	if !IsNil(o.RecipientId) {
		toSerialize["recipient_id"] = o.RecipientId
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.ShipmentNumber) {
		toSerialize["shipment_number"] = o.ShipmentNumber
	}
	if !IsNil(o.TrackingNumber) {
		toSerialize["tracking_number"] = o.TrackingNumber
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.AmountMinor) {
		toSerialize["amount_minor"] = o.AmountMinor
	}
	return toSerialize, nil
}

func (o *WebhookEventData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"letter_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEventData := _WebhookEventData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEventData)

	if err != nil {
		return err
	}

	*o = WebhookEventData(varWebhookEventData)

	return err
}

type NullableWebhookEventData struct {
	value *WebhookEventData
	isSet bool
}

func (v NullableWebhookEventData) Get() *WebhookEventData {
	return v.value
}

func (v *NullableWebhookEventData) Set(val *WebhookEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEventData(val *WebhookEventData) *NullableWebhookEventData {
	return &NullableWebhookEventData{value: val, isSet: true}
}

func (v NullableWebhookEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


