/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Recipient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Recipient{}

// Recipient struct for Recipient
type Recipient struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Address *string `json:"address,omitempty"`
	Status RecipientStatus `json:"status"`
	// Наш трек-номер (РПО), присваивается сразу при создании.
	ShipmentNumber *string `json:"shipment_number,omitempty"`
	// Трек-номер Почты России (ШПИ). Появляется после регистрации отправления.
	TrackingNumber *string `json:"tracking_number,omitempty"`
	// Стоимость отправления этому получателю, в копейках.
	PriceMinor *int64 `json:"price_minor,omitempty"`
	// Причина ошибки (для `failed`).
	Error *string `json:"error,omitempty"`
}

type _Recipient Recipient

// NewRecipient instantiates a new Recipient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecipient(id string, name string, status RecipientStatus) *Recipient {
	this := Recipient{}
	this.Id = id
	this.Name = name
	this.Status = status
	return &this
}

// NewRecipientWithDefaults instantiates a new Recipient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecipientWithDefaults() *Recipient {
	this := Recipient{}
	return &this
}

// GetId returns the Id field value
func (o *Recipient) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Recipient) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Recipient) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Recipient) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Recipient) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Recipient) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Recipient) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Recipient) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Recipient) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *Recipient) SetAddress(v string) {
	o.Address = &v
}

// GetStatus returns the Status field value
func (o *Recipient) GetStatus() RecipientStatus {
	if o == nil {
		var ret RecipientStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Recipient) GetStatusOk() (*RecipientStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Recipient) SetStatus(v RecipientStatus) {
	o.Status = v
}

// GetShipmentNumber returns the ShipmentNumber field value if set, zero value otherwise.
func (o *Recipient) GetShipmentNumber() string {
	if o == nil || IsNil(o.ShipmentNumber) {
		var ret string
		return ret
	}
	return *o.ShipmentNumber
}

// GetShipmentNumberOk returns a tuple with the ShipmentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Recipient) GetShipmentNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ShipmentNumber) {
		return nil, false
	}
	return o.ShipmentNumber, true
}

// HasShipmentNumber returns a boolean if a field has been set.
func (o *Recipient) HasShipmentNumber() bool {
	if o != nil && !IsNil(o.ShipmentNumber) {
		return true
	}

	return false
}

// SetShipmentNumber gets a reference to the given string and assigns it to the ShipmentNumber field.
func (o *Recipient) SetShipmentNumber(v string) {
	o.ShipmentNumber = &v
}

// GetTrackingNumber returns the TrackingNumber field value if set, zero value otherwise.
func (o *Recipient) GetTrackingNumber() string {
	if o == nil || IsNil(o.TrackingNumber) {
		var ret string
		return ret
	}
	return *o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Recipient) GetTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingNumber) {
		return nil, false
	}
	return o.TrackingNumber, true
}

// HasTrackingNumber returns a boolean if a field has been set.
func (o *Recipient) HasTrackingNumber() bool {
	if o != nil && !IsNil(o.TrackingNumber) {
		return true
	}

	return false
}

// SetTrackingNumber gets a reference to the given string and assigns it to the TrackingNumber field.
func (o *Recipient) SetTrackingNumber(v string) {
	o.TrackingNumber = &v
}

// GetPriceMinor returns the PriceMinor field value if set, zero value otherwise.
func (o *Recipient) GetPriceMinor() int64 {
	if o == nil || IsNil(o.PriceMinor) {
		var ret int64
		return ret
	}
	return *o.PriceMinor
}

// GetPriceMinorOk returns a tuple with the PriceMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Recipient) GetPriceMinorOk() (*int64, bool) {
	if o == nil || IsNil(o.PriceMinor) {
		return nil, false
	}
	return o.PriceMinor, true
}

// HasPriceMinor returns a boolean if a field has been set.
func (o *Recipient) HasPriceMinor() bool {
	if o != nil && !IsNil(o.PriceMinor) {
		return true
	}

	return false
}

// SetPriceMinor gets a reference to the given int64 and assigns it to the PriceMinor field.
func (o *Recipient) SetPriceMinor(v int64) {
	o.PriceMinor = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *Recipient) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Recipient) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *Recipient) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *Recipient) SetError(v string) {
	o.Error = &v
}

func (o Recipient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Recipient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.ShipmentNumber) {
		toSerialize["shipment_number"] = o.ShipmentNumber
	}
	if !IsNil(o.TrackingNumber) {
		toSerialize["tracking_number"] = o.TrackingNumber
	}
	if !IsNil(o.PriceMinor) {
		toSerialize["price_minor"] = o.PriceMinor
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *Recipient) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecipient := _Recipient{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecipient)

	if err != nil {
		return err
	}

	*o = Recipient(varRecipient)

	return err
}

type NullableRecipient struct {
	value *Recipient
	isSet bool
}

func (v NullableRecipient) Get() *Recipient {
	return v.value
}

func (v *NullableRecipient) Set(val *Recipient) {
	v.value = val
	v.isSet = true
}

func (v NullableRecipient) IsSet() bool {
	return v.isSet
}

func (v *NullableRecipient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecipient(val *Recipient) *NullableRecipient {
	return &NullableRecipient{value: val, isSet: true}
}

func (v NullableRecipient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecipient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


