/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 49 вложений. Тело запроса — не более 64 МиБ целиком, поэтому крупные и многочисленные файлы передавайте ссылкой (`url`), а не в `base64`.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
)

// checks if the SenderInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SenderInput{}

// SenderInput Отправитель письма. Профиль аккаунта (ЛК) достраивает отправителя ЦЕЛИКОМ или не достраивает совсем: * `sender` не передан, либо в нём только `email` — имя, адрес,   `party_type` и `inn` берутся из профиля. Так отправляют письма от   своего имени, при необходимости переопределив почту плательщика. * в `sender` передано любое из `name`, `address`, `party_type`,   `inn` — отправителем считается ДРУГОЕ лицо, и все четыре поля   берутся строго из запроса. `name`, `address` и `party_type` в   этом режиме ОБЯЗАТЕЛЬНЫ, иначе 422 `sender_incomplete`; `inn`   необязателен — не передали, значит отправитель без ИНН.  `party_type` обязателен намеренно: подставить за вас `individual` значило бы угадать юридическую природу лица, и «ООО «Ромашка»» без типа молча сохранилось бы физлицом. Так отправляют письма от имени своих клиентов: реквизиты владельца аккаунта не подмешиваются к чужому лицу. `email` — исключение: переданный сохраняется как есть, а при отсутствии он достраивается из профиля в любом режиме, потому что это адрес плательщика для кассового чека, а не реквизит отправителя. Коды отказа различают, что чинить: `sender_incomplete` — неполон запрос, `sender_profile_incomplete` — `sender` не передан, а в профиле ЛК нет имени или адреса.
type SenderInput struct {
	// ФИО или название отправителя. Обязательно, если в `sender` передано хоть одно поле отправителя; иначе берётся из профиля ЛК. Строка из одних пробелов считается незаполненной.
	Name *string `json:"name,omitempty"`
	// Адрес отправителя (строкой; нормализуется). Обязателен, если в `sender` передано хоть одно поле отправителя; иначе берётся из профиля ЛК.
	Address *string `json:"address,omitempty"`
	// Email плательщика для кассового чека. Не указан — из профиля ЛК (достраивается всегда).
	Email *string `json:"email,omitempty"`
	PartyType *PartyType `json:"party_type,omitempty"`
	// ИНН отправителя (необязателен): 10 цифр — юрлицо, 12 — физлицо или ИП. ⚠️ Если отправитель описан в запросе, ИНН из профиля НЕ подставляется: не передали — отправитель остаётся без ИНН.
	Inn *string `json:"inn,omitempty" validate:"regexp=^(?:[0-9]{10}|[0-9]{12})$"`
}

// NewSenderInput instantiates a new SenderInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderInput() *SenderInput {
	this := SenderInput{}
	return &this
}

// NewSenderInputWithDefaults instantiates a new SenderInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderInputWithDefaults() *SenderInput {
	this := SenderInput{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SenderInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SenderInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SenderInput) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *SenderInput) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *SenderInput) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *SenderInput) SetAddress(v string) {
	o.Address = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SenderInput) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SenderInput) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SenderInput) SetEmail(v string) {
	o.Email = &v
}

// GetPartyType returns the PartyType field value if set, zero value otherwise.
func (o *SenderInput) GetPartyType() PartyType {
	if o == nil || IsNil(o.PartyType) {
		var ret PartyType
		return ret
	}
	return *o.PartyType
}

// GetPartyTypeOk returns a tuple with the PartyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetPartyTypeOk() (*PartyType, bool) {
	if o == nil || IsNil(o.PartyType) {
		return nil, false
	}
	return o.PartyType, true
}

// HasPartyType returns a boolean if a field has been set.
func (o *SenderInput) HasPartyType() bool {
	if o != nil && !IsNil(o.PartyType) {
		return true
	}

	return false
}

// SetPartyType gets a reference to the given PartyType and assigns it to the PartyType field.
func (o *SenderInput) SetPartyType(v PartyType) {
	o.PartyType = &v
}

// GetInn returns the Inn field value if set, zero value otherwise.
func (o *SenderInput) GetInn() string {
	if o == nil || IsNil(o.Inn) {
		var ret string
		return ret
	}
	return *o.Inn
}

// GetInnOk returns a tuple with the Inn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderInput) GetInnOk() (*string, bool) {
	if o == nil || IsNil(o.Inn) {
		return nil, false
	}
	return o.Inn, true
}

// HasInn returns a boolean if a field has been set.
func (o *SenderInput) HasInn() bool {
	if o != nil && !IsNil(o.Inn) {
		return true
	}

	return false
}

// SetInn gets a reference to the given string and assigns it to the Inn field.
func (o *SenderInput) SetInn(v string) {
	o.Inn = &v
}

func (o SenderInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SenderInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.PartyType) {
		toSerialize["party_type"] = o.PartyType
	}
	if !IsNil(o.Inn) {
		toSerialize["inn"] = o.Inn
	}
	return toSerialize, nil
}

type NullableSenderInput struct {
	value *SenderInput
	isSet bool
}

func (v NullableSenderInput) Get() *SenderInput {
	return v.value
}

func (v *NullableSenderInput) Set(val *SenderInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderInput(val *SenderInput) *NullableSenderInput {
	return &NullableSenderInput{value: val, isSet: true}
}

func (v NullableSenderInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


