/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrackingInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackingInfo{}

// TrackingInfo struct for TrackingInfo
type TrackingInfo struct {
	RecipientId string `json:"recipient_id"`
	ShipmentNumber *string `json:"shipment_number,omitempty"`
	TrackingNumber *string `json:"tracking_number,omitempty"`
	Events []TrackingInfoEventsInner `json:"events"`
}

type _TrackingInfo TrackingInfo

// NewTrackingInfo instantiates a new TrackingInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackingInfo(recipientId string, events []TrackingInfoEventsInner) *TrackingInfo {
	this := TrackingInfo{}
	this.RecipientId = recipientId
	this.Events = events
	return &this
}

// NewTrackingInfoWithDefaults instantiates a new TrackingInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackingInfoWithDefaults() *TrackingInfo {
	this := TrackingInfo{}
	return &this
}

// GetRecipientId returns the RecipientId field value
func (o *TrackingInfo) GetRecipientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientId
}

// GetRecipientIdOk returns a tuple with the RecipientId field value
// and a boolean to check if the value has been set.
func (o *TrackingInfo) GetRecipientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientId, true
}

// SetRecipientId sets field value
func (o *TrackingInfo) SetRecipientId(v string) {
	o.RecipientId = v
}

// GetShipmentNumber returns the ShipmentNumber field value if set, zero value otherwise.
func (o *TrackingInfo) GetShipmentNumber() string {
	if o == nil || IsNil(o.ShipmentNumber) {
		var ret string
		return ret
	}
	return *o.ShipmentNumber
}

// GetShipmentNumberOk returns a tuple with the ShipmentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingInfo) GetShipmentNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ShipmentNumber) {
		return nil, false
	}
	return o.ShipmentNumber, true
}

// HasShipmentNumber returns a boolean if a field has been set.
func (o *TrackingInfo) HasShipmentNumber() bool {
	if o != nil && !IsNil(o.ShipmentNumber) {
		return true
	}

	return false
}

// SetShipmentNumber gets a reference to the given string and assigns it to the ShipmentNumber field.
func (o *TrackingInfo) SetShipmentNumber(v string) {
	o.ShipmentNumber = &v
}

// GetTrackingNumber returns the TrackingNumber field value if set, zero value otherwise.
func (o *TrackingInfo) GetTrackingNumber() string {
	if o == nil || IsNil(o.TrackingNumber) {
		var ret string
		return ret
	}
	return *o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingInfo) GetTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingNumber) {
		return nil, false
	}
	return o.TrackingNumber, true
}

// HasTrackingNumber returns a boolean if a field has been set.
func (o *TrackingInfo) HasTrackingNumber() bool {
	if o != nil && !IsNil(o.TrackingNumber) {
		return true
	}

	return false
}

// SetTrackingNumber gets a reference to the given string and assigns it to the TrackingNumber field.
func (o *TrackingInfo) SetTrackingNumber(v string) {
	o.TrackingNumber = &v
}

// GetEvents returns the Events field value
func (o *TrackingInfo) GetEvents() []TrackingInfoEventsInner {
	if o == nil {
		var ret []TrackingInfoEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *TrackingInfo) GetEventsOk() ([]TrackingInfoEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *TrackingInfo) SetEvents(v []TrackingInfoEventsInner) {
	o.Events = v
}

func (o TrackingInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackingInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recipient_id"] = o.RecipientId
	if !IsNil(o.ShipmentNumber) {
		toSerialize["shipment_number"] = o.ShipmentNumber
	}
	if !IsNil(o.TrackingNumber) {
		toSerialize["tracking_number"] = o.TrackingNumber
	}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *TrackingInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipient_id",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrackingInfo := _TrackingInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrackingInfo)

	if err != nil {
		return err
	}

	*o = TrackingInfo(varTrackingInfo)

	return err
}

type NullableTrackingInfo struct {
	value *TrackingInfo
	isSet bool
}

func (v NullableTrackingInfo) Get() *TrackingInfo {
	return v.value
}

func (v *NullableTrackingInfo) Set(val *TrackingInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackingInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackingInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackingInfo(val *TrackingInfo) *NullableTrackingInfo {
	return &NullableTrackingInfo{value: val, isSet: true}
}

func (v NullableTrackingInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackingInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


