/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
)

// checks if the Party type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Party{}

// Party struct for Party
type Party struct {
	Name *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
	PartyType *PartyType `json:"party_type,omitempty"`
	Inn *string `json:"inn,omitempty"`
}

// NewParty instantiates a new Party object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParty() *Party {
	this := Party{}
	return &this
}

// NewPartyWithDefaults instantiates a new Party object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartyWithDefaults() *Party {
	this := Party{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Party) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Party) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Party) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Party) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Party) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *Party) SetAddress(v string) {
	o.Address = &v
}

// GetPartyType returns the PartyType field value if set, zero value otherwise.
func (o *Party) GetPartyType() PartyType {
	if o == nil || IsNil(o.PartyType) {
		var ret PartyType
		return ret
	}
	return *o.PartyType
}

// GetPartyTypeOk returns a tuple with the PartyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetPartyTypeOk() (*PartyType, bool) {
	if o == nil || IsNil(o.PartyType) {
		return nil, false
	}
	return o.PartyType, true
}

// HasPartyType returns a boolean if a field has been set.
func (o *Party) HasPartyType() bool {
	if o != nil && !IsNil(o.PartyType) {
		return true
	}

	return false
}

// SetPartyType gets a reference to the given PartyType and assigns it to the PartyType field.
func (o *Party) SetPartyType(v PartyType) {
	o.PartyType = &v
}

// GetInn returns the Inn field value if set, zero value otherwise.
func (o *Party) GetInn() string {
	if o == nil || IsNil(o.Inn) {
		var ret string
		return ret
	}
	return *o.Inn
}

// GetInnOk returns a tuple with the Inn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetInnOk() (*string, bool) {
	if o == nil || IsNil(o.Inn) {
		return nil, false
	}
	return o.Inn, true
}

// HasInn returns a boolean if a field has been set.
func (o *Party) HasInn() bool {
	if o != nil && !IsNil(o.Inn) {
		return true
	}

	return false
}

// SetInn gets a reference to the given string and assigns it to the Inn field.
func (o *Party) SetInn(v string) {
	o.Inn = &v
}

func (o Party) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Party) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.PartyType) {
		toSerialize["party_type"] = o.PartyType
	}
	if !IsNil(o.Inn) {
		toSerialize["inn"] = o.Inn
	}
	return toSerialize, nil
}

type NullableParty struct {
	value *Party
	isSet bool
}

func (v NullableParty) Get() *Party {
	return v.value
}

func (v *NullableParty) Set(val *Party) {
	v.value = val
	v.isSet = true
}

func (v NullableParty) IsSet() bool {
	return v.isSet
}

func (v *NullableParty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParty(val *Party) *NullableParty {
	return &NullableParty{value: val, isSet: true}
}

func (v NullableParty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


