/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LetterContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LetterContent{}

// LetterContent Контент письма. Опись формируется автоматически.
type LetterContent struct {
	MainFile FileSource `json:"main_file"`
	Attachments []FileSource `json:"attachments,omitempty"`
}

type _LetterContent LetterContent

// NewLetterContent instantiates a new LetterContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLetterContent(mainFile FileSource) *LetterContent {
	this := LetterContent{}
	this.MainFile = mainFile
	return &this
}

// NewLetterContentWithDefaults instantiates a new LetterContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLetterContentWithDefaults() *LetterContent {
	this := LetterContent{}
	return &this
}

// GetMainFile returns the MainFile field value
func (o *LetterContent) GetMainFile() FileSource {
	if o == nil {
		var ret FileSource
		return ret
	}

	return o.MainFile
}

// GetMainFileOk returns a tuple with the MainFile field value
// and a boolean to check if the value has been set.
func (o *LetterContent) GetMainFileOk() (*FileSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MainFile, true
}

// SetMainFile sets field value
func (o *LetterContent) SetMainFile(v FileSource) {
	o.MainFile = v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *LetterContent) GetAttachments() []FileSource {
	if o == nil || IsNil(o.Attachments) {
		var ret []FileSource
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LetterContent) GetAttachmentsOk() ([]FileSource, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *LetterContent) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []FileSource and assigns it to the Attachments field.
func (o *LetterContent) SetAttachments(v []FileSource) {
	o.Attachments = v
}

func (o LetterContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LetterContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["main_file"] = o.MainFile
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	return toSerialize, nil
}

func (o *LetterContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"main_file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLetterContent := _LetterContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLetterContent)

	if err != nil {
		return err
	}

	*o = LetterContent(varLetterContent)

	return err
}

type NullableLetterContent struct {
	value *LetterContent
	isSet bool
}

func (v NullableLetterContent) Get() *LetterContent {
	return v.value
}

func (v *NullableLetterContent) Set(val *LetterContent) {
	v.value = val
	v.isSet = true
}

func (v NullableLetterContent) IsSet() bool {
	return v.isSet
}

func (v *NullableLetterContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLetterContent(val *LetterContent) *NullableLetterContent {
	return &NullableLetterContent{value: val, isSet: true}
}

func (v NullableLetterContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLetterContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


