/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"fmt"
)

// PartyType Тип лица — физическое или юридическое.
type PartyType string

// List of PartyType
const (
	INDIVIDUAL PartyType = "individual"
	ORGANIZATION PartyType = "organization"
)

// All allowed values of PartyType enum
var AllowedPartyTypeEnumValues = []PartyType{
	"individual",
	"organization",
}

func (v *PartyType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PartyType(value)
	for _, existing := range AllowedPartyTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PartyType", value)
}

// NewPartyTypeFromValue returns a pointer to a valid PartyType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPartyTypeFromValue(v string) (*PartyType, error) {
	ev := PartyType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PartyType: valid values are %v", v, AllowedPartyTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PartyType) IsValid() bool {
	for _, existing := range AllowedPartyTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PartyType value
func (v PartyType) Ptr() *PartyType {
	return &v
}

type NullablePartyType struct {
	value *PartyType
	isSet bool
}

func (v NullablePartyType) Get() *PartyType {
	return v.value
}

func (v *NullablePartyType) Set(val *PartyType) {
	v.value = val
	v.isSet = true
}

func (v NullablePartyType) IsSet() bool {
	return v.isSet
}

func (v *NullablePartyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartyType(val *PartyType) *NullablePartyType {
	return &NullablePartyType{value: val, isSet: true}
}

func (v NullablePartyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

