/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
)

// checks if the FileSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileSource{}

// FileSource Источник PDF-файла. Укажите **ровно один** способ: - `base64` — содержимое файла в base64 (для небольших файлов); - `url` — HTTPS-ссылка, файл скачивается потоково (для крупных файлов,   чтобы не передавать тело в base64). Лимиты по размеру/страницам — см. документацию; тип файла — только PDF. 
type FileSource struct {
	// PDF в base64.
	Base64 *string `json:"base64,omitempty"`
	// HTTPS-ссылка на PDF (скачиваем потоково).
	Url *string `json:"url,omitempty"`
	// Имя файла (опционально, для отображения).
	Filename *string `json:"filename,omitempty"`
}

// NewFileSource instantiates a new FileSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSource() *FileSource {
	this := FileSource{}
	return &this
}

// NewFileSourceWithDefaults instantiates a new FileSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSourceWithDefaults() *FileSource {
	this := FileSource{}
	return &this
}

// GetBase64 returns the Base64 field value if set, zero value otherwise.
func (o *FileSource) GetBase64() string {
	if o == nil || IsNil(o.Base64) {
		var ret string
		return ret
	}
	return *o.Base64
}

// GetBase64Ok returns a tuple with the Base64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSource) GetBase64Ok() (*string, bool) {
	if o == nil || IsNil(o.Base64) {
		return nil, false
	}
	return o.Base64, true
}

// HasBase64 returns a boolean if a field has been set.
func (o *FileSource) HasBase64() bool {
	if o != nil && !IsNil(o.Base64) {
		return true
	}

	return false
}

// SetBase64 gets a reference to the given string and assigns it to the Base64 field.
func (o *FileSource) SetBase64(v string) {
	o.Base64 = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FileSource) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSource) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FileSource) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FileSource) SetUrl(v string) {
	o.Url = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *FileSource) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSource) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *FileSource) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *FileSource) SetFilename(v string) {
	o.Filename = &v
}

func (o FileSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Base64) {
		toSerialize["base64"] = o.Base64
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	return toSerialize, nil
}

type NullableFileSource struct {
	value *FileSource
	isSet bool
}

func (v NullableFileSource) Get() *FileSource {
	return v.value
}

func (v *NullableFileSource) Set(val *FileSource) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSource) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSource(val *FileSource) *NullableFileSource {
	return &NullableFileSource{value: val, isSet: true}
}

func (v NullableFileSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


