/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"fmt"
)

// LetterStatus Жизненный цикл письма. Финальные: `sent`, `partial_failure`, `error`, `cancelled`. 
type LetterStatus string

// List of LetterStatus
const (
	FORMING LetterStatus = "forming"
	AWAITING_PAYMENT LetterStatus = "awaiting_payment"
	PAID LetterStatus = "paid"
	SENDING LetterStatus = "sending"
	SENT LetterStatus = "sent"
	PARTIAL_FAILURE LetterStatus = "partial_failure"
	ERROR LetterStatus = "error"
	CANCELLED LetterStatus = "cancelled"
)

// All allowed values of LetterStatus enum
var AllowedLetterStatusEnumValues = []LetterStatus{
	"forming",
	"awaiting_payment",
	"paid",
	"sending",
	"sent",
	"partial_failure",
	"error",
	"cancelled",
}

func (v *LetterStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LetterStatus(value)
	for _, existing := range AllowedLetterStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LetterStatus", value)
}

// NewLetterStatusFromValue returns a pointer to a valid LetterStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLetterStatusFromValue(v string) (*LetterStatus, error) {
	ev := LetterStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LetterStatus: valid values are %v", v, AllowedLetterStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LetterStatus) IsValid() bool {
	for _, existing := range AllowedLetterStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LetterStatus value
func (v LetterStatus) Ptr() *LetterStatus {
	return &v
}

type NullableLetterStatus struct {
	value *LetterStatus
	isSet bool
}

func (v NullableLetterStatus) Get() *LetterStatus {
	return v.value
}

func (v *NullableLetterStatus) Set(val *LetterStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableLetterStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableLetterStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLetterStatus(val *LetterStatus) *NullableLetterStatus {
	return &NullableLetterStatus{value: val, isSet: true}
}

func (v NullableLetterStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLetterStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

