/*
Doslano Integration API

Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doslano

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecipientInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecipientInput{}

// RecipientInput struct for RecipientInput
type RecipientInput struct {
	// ФИО или название получателя. При resolve_address_by_inn=true ПЕРЕЗАПИСЫВАЕТСЯ наименованием из ЕГРЮЛ.
	Name string `json:"name"`
	// Адрес получателя (строкой; нормализуется на нашей стороне). Можно опустить при resolve_address_by_inn=true.
	Address *string `json:"address,omitempty"`
	PartyType *PartyType `json:"party_type,omitempty"`
	// ИНН (10 цифр).
	Inn *string `json:"inn,omitempty" validate:"regexp=^[0-9]{10}$"`
	// Email получателя для уведомления-копии (опционально). После отправки письма получателю на этот адрес приходит письмо со ссылкой на электронную версию (страница /receive). Пустой/опущен — уведомление не шлётся; адрес указывает отправитель и отвечает за корректность.
	Email *string `json:"email,omitempty"`
	// Авто-резолв адреса по ИНН из ЕГРЮЛ. Работает только для party_type=organization с заданным inn: адрес и наименование берутся из реестра (DaData findById/party, головная организация), address можно не передавать. Если резолв не удался и address не передан — 422 recipient_address_unresolved; флаг без inn или не для organization — 422 recipient_resolve_requires_inn. Если передан и address — он fallback при неудаче резолва.
	ResolveAddressByInn *bool `json:"resolve_address_by_inn,omitempty"`
	// Согласие на усечение адреса до номера дома, если полный адрес не проходит в Почте России (ЕПС валидирует адреса по ГАР, где помещение/офис/комната часто не зарегистрированы). Усечённая форма готовится автоматически: из данных DaData при создании письма (только когда дом распознан ФИАС), а если DaData дом не распознал — из разбора адреса Почтой России при отправке (только когда Почта распознала дом или владение). Триггеры: провал валидации адреса Почтой — проверка не блокирует письмо, пока есть варианты (административная форма → муниципальная → усечённая до дома), — и ошибка сохранения отправления SHIPMENT_ERROR — варианты перебираются сразу, без повторных попыток отправки. (Ошибка регистрации EPS_61_INVALID_ADDRESS обрабатывается независимо существующим механизмом муниципального fallback-адреса, без усечения.) Письмо, ушедшее на усечённый адрес, помечается `address_truncation_applied: true` у получателя. Если не помог ни один вариант — стандартная ошибка (422 при создании либо `failed` + возврат средств).
	AllowAddressTruncation *bool `json:"allow_address_truncation,omitempty"`
}

type _RecipientInput RecipientInput

// NewRecipientInput instantiates a new RecipientInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecipientInput(name string) *RecipientInput {
	this := RecipientInput{}
	this.Name = name
	var resolveAddressByInn bool = false
	this.ResolveAddressByInn = &resolveAddressByInn
	var allowAddressTruncation bool = false
	this.AllowAddressTruncation = &allowAddressTruncation
	return &this
}

// NewRecipientInputWithDefaults instantiates a new RecipientInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecipientInputWithDefaults() *RecipientInput {
	this := RecipientInput{}
	var resolveAddressByInn bool = false
	this.ResolveAddressByInn = &resolveAddressByInn
	var allowAddressTruncation bool = false
	this.AllowAddressTruncation = &allowAddressTruncation
	return &this
}

// GetName returns the Name field value
func (o *RecipientInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RecipientInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RecipientInput) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *RecipientInput) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientInput) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *RecipientInput) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *RecipientInput) SetAddress(v string) {
	o.Address = &v
}

// GetPartyType returns the PartyType field value if set, zero value otherwise.
func (o *RecipientInput) GetPartyType() PartyType {
	if o == nil || IsNil(o.PartyType) {
		var ret PartyType
		return ret
	}
	return *o.PartyType
}

// GetPartyTypeOk returns a tuple with the PartyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientInput) GetPartyTypeOk() (*PartyType, bool) {
	if o == nil || IsNil(o.PartyType) {
		return nil, false
	}
	return o.PartyType, true
}

// HasPartyType returns a boolean if a field has been set.
func (o *RecipientInput) HasPartyType() bool {
	if o != nil && !IsNil(o.PartyType) {
		return true
	}

	return false
}

// SetPartyType gets a reference to the given PartyType and assigns it to the PartyType field.
func (o *RecipientInput) SetPartyType(v PartyType) {
	o.PartyType = &v
}

// GetInn returns the Inn field value if set, zero value otherwise.
func (o *RecipientInput) GetInn() string {
	if o == nil || IsNil(o.Inn) {
		var ret string
		return ret
	}
	return *o.Inn
}

// GetInnOk returns a tuple with the Inn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientInput) GetInnOk() (*string, bool) {
	if o == nil || IsNil(o.Inn) {
		return nil, false
	}
	return o.Inn, true
}

// HasInn returns a boolean if a field has been set.
func (o *RecipientInput) HasInn() bool {
	if o != nil && !IsNil(o.Inn) {
		return true
	}

	return false
}

// SetInn gets a reference to the given string and assigns it to the Inn field.
func (o *RecipientInput) SetInn(v string) {
	o.Inn = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *RecipientInput) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientInput) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *RecipientInput) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *RecipientInput) SetEmail(v string) {
	o.Email = &v
}

// GetResolveAddressByInn returns the ResolveAddressByInn field value if set, zero value otherwise.
func (o *RecipientInput) GetResolveAddressByInn() bool {
	if o == nil || IsNil(o.ResolveAddressByInn) {
		var ret bool
		return ret
	}
	return *o.ResolveAddressByInn
}

// GetResolveAddressByInnOk returns a tuple with the ResolveAddressByInn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientInput) GetResolveAddressByInnOk() (*bool, bool) {
	if o == nil || IsNil(o.ResolveAddressByInn) {
		return nil, false
	}
	return o.ResolveAddressByInn, true
}

// HasResolveAddressByInn returns a boolean if a field has been set.
func (o *RecipientInput) HasResolveAddressByInn() bool {
	if o != nil && !IsNil(o.ResolveAddressByInn) {
		return true
	}

	return false
}

// SetResolveAddressByInn gets a reference to the given bool and assigns it to the ResolveAddressByInn field.
func (o *RecipientInput) SetResolveAddressByInn(v bool) {
	o.ResolveAddressByInn = &v
}

// GetAllowAddressTruncation returns the AllowAddressTruncation field value if set, zero value otherwise.
func (o *RecipientInput) GetAllowAddressTruncation() bool {
	if o == nil || IsNil(o.AllowAddressTruncation) {
		var ret bool
		return ret
	}
	return *o.AllowAddressTruncation
}

// GetAllowAddressTruncationOk returns a tuple with the AllowAddressTruncation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientInput) GetAllowAddressTruncationOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowAddressTruncation) {
		return nil, false
	}
	return o.AllowAddressTruncation, true
}

// HasAllowAddressTruncation returns a boolean if a field has been set.
func (o *RecipientInput) HasAllowAddressTruncation() bool {
	if o != nil && !IsNil(o.AllowAddressTruncation) {
		return true
	}

	return false
}

// SetAllowAddressTruncation gets a reference to the given bool and assigns it to the AllowAddressTruncation field.
func (o *RecipientInput) SetAllowAddressTruncation(v bool) {
	o.AllowAddressTruncation = &v
}

func (o RecipientInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecipientInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.PartyType) {
		toSerialize["party_type"] = o.PartyType
	}
	if !IsNil(o.Inn) {
		toSerialize["inn"] = o.Inn
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.ResolveAddressByInn) {
		toSerialize["resolve_address_by_inn"] = o.ResolveAddressByInn
	}
	if !IsNil(o.AllowAddressTruncation) {
		toSerialize["allow_address_truncation"] = o.AllowAddressTruncation
	}
	return toSerialize, nil
}

func (o *RecipientInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecipientInput := _RecipientInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecipientInput)

	if err != nil {
		return err
	}

	*o = RecipientInput(varRecipientInput)

	return err
}

type NullableRecipientInput struct {
	value *RecipientInput
	isSet bool
}

func (v NullableRecipientInput) Get() *RecipientInput {
	return v.value
}

func (v *NullableRecipientInput) Set(val *RecipientInput) {
	v.value = val
	v.isSet = true
}

func (v NullableRecipientInput) IsSet() bool {
	return v.isSet
}

func (v *NullableRecipientInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecipientInput(val *RecipientInput) *NullableRecipientInput {
	return &NullableRecipientInput{value: val, isSet: true}
}

func (v NullableRecipientInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecipientInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


